"""Conftest for pytest."""
import pytest
from scanmst import Event, Insertion, MicroHomology, NovelInsertion, Read
from scanmst.base import Intervals, MappingMode
from scanmst.graph import Edge, EdgeData, NLPath, Node, NodeIdentity

from tests import FakeBlat, FakeLogger


@pytest.fixture(scope="session")
def fake_logger():
    """Fake logger."""
    return FakeLogger()


@pytest.fixture(scope="session")
def fake_blat():
    """Fake blat."""
    return FakeBlat()


@pytest.fixture()
def novel_insertion():
    """Novel insertion."""
    return NovelInsertion(hit_num=0, query_sequence="ATCA")


@pytest.fixture()
def microhomology():
    """Microhomology."""
    return MicroHomology(query_sequence="ATCA")


@pytest.fixture()
def insertion():
    """Insertion."""
    return Insertion(
        hit_num=1,
        chrom="1",
        ref_start=1,
        strand="+",
        cigarstring="1S2M1S",
        mapq=60,
        nm=0,
        query_sequence="AGCT",
        query_qualities=[10, 20, 10, 9],
    )


@pytest.fixture()
def nodes() -> list[Node]:
    """Return a two-node chain: chr2 (HEAD) -> chr17 (TAIL).

    The coordinates are the TRA/TDUP scenario the suite has always used; only
    the construction changed. ``sv_type``/``modes``/``sr`` used to live on the
    Node and are now edge properties -- see the ``edges`` fixture.
    """
    param_dict = [
        # n1: two exons, so it has exactly one intron (190659995, 190670325)
        {
            "query_name": "one,two",
            "chrom": "chr2",
            "strand": "+",
            "ref_start": 190659106,
            "ref_end": 190670461,
            "identity": NodeIdentity.HEAD,
            "exons": Intervals.from_list([[190659106, 190659995], [190670325, 190670461]]),
        },
        # n2: single exon, so it has no introns
        {
            "query_name": "one,three,two",
            "chrom": "chr17",
            "strand": "+",
            "ref_start": 49502062,
            "ref_end": 49502204,
            "identity": NodeIdentity.TAIL,
            "exons": Intervals.from_list([[49502062, 49502204]]),
        },
    ]
    return [Node(**params) for params in param_dict]


@pytest.fixture()
def edge_data(event) -> EdgeData:
    """Edge payload derived from the shared TDUP event fixture."""
    return EdgeData.from_event(event, read_id="one")


@pytest.fixture()
def edge(nodes, edge_data) -> Edge:
    """The single edge joining the two nodes of the `nodes` fixture."""
    return Edge.from_nodes(nodes[0], nodes[1], edge_data)


@pytest.fixture()
def nlpath(nodes, edge) -> NLPath:
    """An NLPath over `nodes`, wired with the edge between them.

    Neighbour bookkeeping (`update_next_and_previous_node_in_nlpath`) reads
    `nlpath.edges`, so the edge has to be registered for the path to be usable.
    """
    path = NLPath(list(nodes))
    path.add_edge(nodes[0], nodes[1], edge)
    return path


@pytest.fixture()
def read_param_dict():
    """Return a dict of read parameters."""
    return [
        {
            "chrom": "chr17",
            "ref_start": 7701655,
            "strand": "+",
            "cigar_str": "711S734M",
            "mapq": 60,
            "nm": 0,
            "query_seq": "CGCCCGGTCCCCGGCTCCCCCAGTCCCCCACTTAGGCGGGCTCACAGATCCCGGGGTG"
            "CTGGCGCGTGGGCCGGGGGCGCGTAGGGCGCCTGCAGACGGCCCCTGGAAGGGCTCTG"
            "GTGGGGCTGAGCGCTCTGCCGCGGGGGCGCGGGCACAGCAGGAAGCAGGTCCGCGTGG"
            "GCGCTGGGGGCATCAGCTACCGGGGTGGTCCGGGCTGAAGAGCCAGGCAGCCAAGGCA"
            "GCCACCCCGGGGGGTGGGCGACTTTGGGGGAGTTGGTGCCCCGCCCCCCAGGCCTTGG"
            "CGGGGTCATGGGGCCCCCCCATTCTGGGCCGGGGGGCGTGCGAGTCGGGGCCCTGCTG"
            "CTGCTGGGGGTTTTGGGGCTGGTGTCTGGGCTCAGCCTGGAGCCTGTCTACTGGAACT"
            "CGGCGAATAAGAGGTTCCAGGCAGAGGGTGGTTATGTGCTGTACCCTCAGATCGGGGA"
            "CCGGCTAGACCTGCTCTGCCCCCGGGCCCGGCCTCCTGGCCCTCACTCCTCTCCTAAT"
            "TATGAGTTCTACAAGCTGTACCTGGTAGGGGGTGCTCAGGGCCGGCGCTGTGAGGCAC"
            "CCCCTGCCCCAAACCTCCTTCTCACTTGTGATCGCCCAGACCTGGATCTCCGCTTCAC"
            "CATCAAGTTCCAGGAGTATAGCCCTAATCTCTGGGGCCACGAGTTCCGCTCGCACCAC"
            "GATTACTACATCATTGGATGAGCTGACGGCAGCCCATTCGCTCTGCTTCTCCCCGGAT"
            "GGCTCCCAGCTCTTCTGTGGCTTCAACCGGACTGTGCGTGTTTTTTCCACGGCCCGGC"
            "CTGGCCGAGACTGCGAGGTCCGAGCCACATTTGGTAAGCATCTGTGCCTCCAAGGGAG"
            "GAGGAGAGGGAAGGGCACTGCCACCTGCACAGGGGCCTTTTGTGAGCCGGGGGCCACC"
            "TGTGGGGGTTCACGCCGTCCTCTGTACGGCCCCGGGAGCAGGTGCAGCCCAGTCGGCA"
            "GAGGAGCAAACAGGCTCAGAGCAGGTAGGAAACCTTCCCAAGGCCAACCAGCTGGTCAA"
            "AGGACTGCTTCCTTCCTGAACTCATACCCTGTCAGCTGTGGAGCTTTTGGTCTCTGAAA"
            "TCTTTCTAGAAAATTGTTGATAAAGCTGATTCCGTTTTCCTGTAGGCCTTCAACTTGCA"
            "TCTCTCCAAGGAAGAACTGGGATTTGAGAGGGATGAAGTGGGGCTTGGGCATTTAGGTC"
            "CTTTGGGAGGATAGATGTGGGGAGCATCAGAGGTCTTTGTCCTGCTTGTGACAGACAGC"
            "ATGGGGGGGATGTTGAGTCCAAGCATGTTGGTGCTGGGACGGGAGACAGACCTCTGCTT"
            "AGCCTGGTTAGTGCCAGGAGCCATTGCCCCCTCCCCCACTTTGTTCCTTCCCTCTCTAG"
            "CAAAAAAGCAGGGCCAGAGCGGCATCATCTCCTGCATAGCCTTCAG",
            "query_name": "B",
            "lt_soft_len": 711,
            "rt_soft_len": 0,
            "read_match_size": 734,
            "reference_match_size": 734,
            "indel_size": 0,
            "cigartuples_without_soft": [[0, 734]],
            "cigartuples": [(4, 711), (0, 734)],
            "query_length": 1445,
            "mode": 2,
            "sms": (711, 734, 0),
            "ref_end": 7702389,
        },
        {
            "chrom": "chr17",
            "ref_start": 7705301,
            "strand": "+",
            "cigar_str": "419M2237N294M732S",
            "mapq": 60,
            "nm": 0,
            "query_seq": "CGCCCGGTCCCCGGCTCCCCCAGTCCCCCACTTAGGCGGGCTCACAGATCCCGGGGTG"
            "CTGGCGCGTGGGCCGGGGGCGCGTAGGGCGCCTGCAGACGGCCCCTGGAAGGGCTCTG"
            "GTGGGGCTGAGCGCTCTGCCGCGGGGGCGCGGGCACAGCAGGAAGCAGGTCCGCGTGG"
            "GCGCTGGGGGCATCAGCTACCGGGGTGGTCCGGGCTGAAGAGCCAGGCAGCCAAGGCA"
            "GCCACCCCGGGGGGTGGGCGACTTTGGGGGAGTTGGTGCCCCGCCCCCCAGGCCTTGG"
            "CGGGGTCATGGGGCCCCCCCATTCTGGGCCGGGGGGCGTGCGAGTCGGGGCCCTGCTG"
            "CTGCTGGGGGTTTTGGGGCTGGTGTCTGGGCTCAGCCTGGAGCCTGTCTACTGGAACT"
            "CGGCGAATAAGAGGTTCCAGGCAGAGGGTGGTTATGTGCTGTACCCTCAGATCGGGGA"
            "CCGGCTAGACCTGCTCTGCCCCCGGGCCCGGCCTCCTGGCCCTCACTCCTCTCCTAAT"
            "TATGAGTTCTACAAGCTGTACCTGGTAGGGGGTGCTCAGGGCCGGCGCTGTGAGGCAC"
            "CCCCTGCCCCAAACCTCCTTCTCACTTGTGATCGCCCAGACCTGGATCTCCGCTTCAC"
            "CATCAAGTTCCAGGAGTATAGCCCTAATCTCTGGGGCCACGAGTTCCGCTCGCACCAC"
            "GATTACTACATCATTGGATGAGCTGACGGCAGCCCATTCGCTCTGCTTCTCCCCGGAT"
            "GGCTCCCAGCTCTTCTGTGGCTTCAACCGGACTGTGCGTGTTTTTTCCACGGCCCGGC"
            "CTGGCCGAGACTGCGAGGTCCGAGCCACATTTGGTAAGCATCTGTGCCTCCAAGGGAG"
            "GAGGAGAGGGAAGGGCACTGCCACCTGCACAGGGGCCTTTTGTGAGCCGGGGGCCACC"
            "TGTGGGGGTTCACGCCGTCCTCTGTACGGCCCCGGGAGCAGGTGCAGCCCAGTCGGCA"
            "GAGGAGCAAACAGGCTCAGAGCAGGTAGGAAACCTTCCCAAGGCCAACCAGCTGGTCA"
            "AAGGACTGCTTCCTTCCTGAACTCATACCCTGTCAGCTGTGGAGCTTTTGGTCTCTGA"
            "AATCTTTCTAGAAAATTGTTGATAAAGCTGATTCCGTTTTCCTGTAGGCCTTCAACTT"
            "GCATCTCTCCAAGGAAGAACTGGGATTTGAGAGGGATGAAGTGGGGCTTGGGCATTTA"
            "GGTCCTTTGGGAGGATAGATGTGGGGAGCATCAGAGGTCTTTGTCCTGCTTGTGACAG"
            "ACAGCATGGGGGGGATGTTGAGTCCAAGCATGTTGGTGCTGGGACGGGAGACAGACCT"
            "CTGCTTAGCCTGGTTAGTGCCAGGAGCCATTGCCCCCTCCCCCACTTTGTTCCTTCCC"
            "TCTCTAGCAAAAAAGCAGGGCCAGAGCGGCATCATCTCCTGCATAGCCTTCAG",
            "query_name": "B",
            "lt_soft_len": 0,
            "rt_soft_len": 732,
            "read_match_size": 713,
            "reference_match_size": 2950,
            "indel_size": 2237,
            "cigartuples_without_soft": [[0, 419], [3, 2237], [0, 294]],
            "cigartuples": [(0, 419), (3, 2237), (0, 294), (4, 732)],
            "query_length": 1445,
            "adhocsms": None,
            "adhocseq": None,
            "mode": 1,
            "sms": (0, 713, 732),
            "ref_end": 7708251,
        },
    ]


@pytest.fixture()
def reads(read_param_dict):
    """Reads fixture."""
    read_init_params = [
        "query_name",
        "chrom",
        "ref_start",
        "strand",
        "cigar_str",
        "mapq",
        "nm",
        "query_seq",
    ]

    read_instances = []
    for read_param in read_param_dict:
        # Read.new requires query_qualities, and the realignment path in
        # ReadsConnector rejects None, so give every base a flat Phred 30.
        temp = Read.new(
            **{param: read_param[param] for param in read_init_params},  # type: ignore
            query_qualities=[30] * len(read_param["query_seq"]),
        )
        read_instances.append(temp)
    return read_instances


@pytest.fixture()
def event():
    """Event fixture."""
    event_tuple = (
        "TDUP",  # svtype
        0,  # annotation_code
        1,  # splicing code
        # bp1, bp2, mode1, mode2. The modes are MappingMode members, not bare
        # ints: reorder_event() keys its lookup table off `mode.value`.
        ("chr17:7701655", "chr17:7708249", MappingMode.SM, MappingMode.MS),
        (7701655, 7702389, [[7701655, 7702389]]),  # r1 start, r1 end, r1 exons
        (7705301, 7708251, [[7705301, 7705720], [7707957, 7708251]]),  # r2
        ("-GG", "-GG"),  # insertions info
        ("+", "+"),  # strand1, strand2
        ["INTERGENIC", "INTERGENIC"],  # gene1, gene2
        False,  # is_read_reversed
    )

    return Event(event_tuple)  # type: ignore


@pytest.fixture()
def inv_reads():
    """Reads fixture."""
    read_init_params = [
        "query_name",
        "chrom",
        "ref_start",
        "strand",
        "cigar_str",
        "mapq",
        "nm",
        "query_seq",
    ]

    param_dict = [
        {
            "chrom": "chr17",
            "ref_start": 1650628,
            "strand": "-",
            "cigar_str": "328M151N203M103N141M935S",
            "mapq": 60,
            "nm": 0,
            "query_seq": "TCCTATTTATACAAAATTTATTATTATATTTTATTCAGGATGACAAGCCA"
            "TCAGGAGGTCAACAACACAAGCACAGACAGAGGGAAAGAGGCCAAACTGC"
            "TGAATGTCAGCGGCCTGTCTGGAGGGGCTGAGGCTTCGGCCTCGGGAGGC"
            "TGAAGCAGGAGGCAGGGAAACGGTCAGGCATACAGGTCCTCCCGATCCGC"
            "AGAGTAAACCTCCCCCTCCTGCAGGAGAGCAAAGTTGAGGAAGTGAGAGG"
            "GCCTGTGCACCTCGTGGTAGAACTCTTTGGGGTTCGCCAGCTGTAGCTCA"
            "TATTTCATGTTGGGGTCATGCCGAACACCCATGAAGTTGTAGTTCCACGA"
            "GGACTGGGCAGGGACCATGAAGAAGCCAAGGAAACGGTCCGACAGCAGCA"
            "TCTGCACCCTCTCATAGTGTGAAGGCAGGTAGCCCTTGGGGTTGTTGCCC"
            "TTGTCTGTGTTCTGGCGGCCCCATTCGTAGCCACTGGGGGTCAGCTTGTA"
            "GGCCGTCAGTGTACAGGAGCCTGGCGTGAAGCTGCATGTGATGATAATGG"
            "TCTTCTCGCCATCCCAAGATGGGTTGTCAGCCATGATCTTGGCATGGGTG"
            "GTGACATCCTGGGGTGATAACTGCGGGGACTCATTGGGCTGAGTGTGGAT"
            "CCAACCTAAGGGTTCCATCTCCAGGTAGCTGATGTAGGGCAGGTACTGGT"
            "AGGTGAGGACAGGCTCCCCATACAGGCGGGCGATGTGGAGGAGGCAGCTG"
            "AGCACAGGCCCTGACACGATGTCGCCCAGGACCGGCCTCTTCTGGTAGAT"
            "GTTGCCGGCGCTCAGCGGTGGGCTCTCGCCACTGCTCACTGTGAACTGCT"
            "GCCGAGTGGGTCCAACATAACAAGACGTCAGCAGGCGGAGCAGGTTCCGG"
            "GCCACGTGGCGAGAGGCCACTGTGGGGCCGAGCTTGGCAGACAGCCAGCG"
            "GACCATCTTGCAGGCTGTATCAAGGAGGATCTTCTGTTCTTTGCCTTCTG"
            "ACTGCTCAGGCAGTGCCTCCTCCTCTTCTTCTCCATCTCCCCCACTGCCG"
            "CCGGCCACAACCGTCTCCATGGACAGCACCGTGTCAGACAGAGTGAGCTC"
            "AGATGCCCCGGTGACCTCCTCCTGCTCCCCCTCCTCCTCCTCTAGCACCA"
            "CGCAGCTGTCCTCCTCCTCCTCTTCCTCCTCGGAGCCCTCGCTTTGCTTC"
            "AAGTCCTGGCTGCTGTCACCTGATCGAAGGCTGCTCTTGTCCACGGGGGC"
            "ACCCCCCTCGTCTGGAGCCCGCTCCTCACCCAGGGAGGTCTCGCTGGTGC"
            "TGCTCTTGTCACTCAGCCGGCCCAGGCTCACAGCCTCAGCCTCCTGGGGC"
            "TGGGGAGACTCAGTCACATAGAGCCCGGCTTGGAAGTCCTCTGTCTCAGG"
            "GAGGTCAGCCTGGTCGTGGAAGCTGACGCCAGACGTGTAGTCTGGGAGCC"
            "CCAGGCCCGAGGAGGCAGGAGGCTCCCCATCCATGGGAATCTCCTCCCCA"
            "AAAGCACAGGAGCCAGGCCCGGCCCCGGGCAGCCCGCTCTCCTCCTCCTC"
            "AGCAGCCCCTGCCAGGTCCTTGCTCTCCTCCTGGGAGGCCTCTGCGCCCG"
            "CCAGCAC",
            "query_name": "four",
            "lt_soft_len": 0,
            "rt_soft_len": 935,
            "read_match_size": 672,
            "reference_match_size": 926,
            "indel_size": 254,
            "cigartuples_without_soft": [
                [0, 328],
                [3, 151],
                [0, 203],
                [3, 103],
                [0, 141],
            ],
            "cigartuples": [(0, 328), (3, 151), (0, 203), (3, 103), (0, 141), (4, 935)],
            "query_length": 1607,
            "adhocsms": None,
            "adhocseq": None,
            "mode": None,
            "sms": (0, 672, 935),
            "ref_end": 1651554,
        },
        {
            "chrom": "chr17",
            "ref_start": 1727989,
            "strand": "+",
            "cigar_str": "637M1753N108M267N192M670S",
            "mapq": 60,
            "nm": 0,
            "query_seq": "GTGCTGGCGGGCGCAGAGGCCTCCCAGGAGGAGAGCAAGGACCTGGCAGG"
            "GGCTGCTGAGGAGGAGGAGAGCGGGCTGCCCGGGGCCGGGCCTGGCTCCT"
            "GTGCTTTTGGGGAGGAGATTCCCATGGATGGGGAGCCTCCTGCCTCCTCG"
            "GGCCTGGGGCTCCCAGACTACACGTCTGGCGTCAGCTTCCACGACCAGGC"
            "TGACCTCCCTGAGACAGAGGACTTCCAAGCCGGGCTCTATGTGACTGAGT"
            "CTCCCCAGCCCCAGGAGGCTGAGGCTGTGAGCCTGGGCCGGCTGAGTGAC"
            "AAGAGCAGCACCAGCGAGACCTCCCTGGGTGAGGAGCGGGCTCCAGACGA"
            "GGGGGGTGCCCCCGTGGACAAGAGCAGCCTTCGATCAGGTGACAGCAGCC"
            "AGGACTTGAAGCAAAGCGAGGGCTCCGAGGAGGAAGAGGAGGAGGAGGAC"
            "AGCTGCGTGGTGCTAGAGGAGGAGGAGGGGGAGCAGGAGGAGGTCACCGG"
            "GGCATCTGAGCTCACTCTGTCTGACACGGTGCTGTCCATGGAGACGGTTG"
            "TGGCCGGCGGCAGTGGGGGAGATGGAGAAGAAGAGGAGGAGGCACTGCCT"
            "GAGCAGTCAGAAGGCAAAGAACAGAAGATCCTCCTTGATACAGCCTGCAA"
            "GATGGTCCGCTGGCTGTCTGCCAAGCTCGGCCCCACAGTGGCCTCTCGCC"
            "ACGTGGCCCGGAACCTGCTCCGCCTGCTGACGTCTTGTTATGTTGGACCC"
            "ACTCGGCAGCAGTTCACAGTGAGCAGTGGCGAGAGCCCACCGCTGAGCGC"
            "CGGCAACATCTACCAGAAGAGGCCGGTCCTGGGCGACATCGTGTCAGGGC"
            "CTGTGCTCAGCTGCCTCCTCCACATCGCCCGCCTGTATGGGGAGCCTGTC"
            "CTCACCTACCAGTACCTGCCCTACATCAGCTACCTGGAGATGGAACCCTT"
            "AGGTTGGATCCACACTCAGCCCAATGAGTCCCCGCAGTTATCACCCCAGG"
            "ATGTCACCACCCATGCCAAGATCATGGCTGACAACCCATCTTGGGATGGC"
            "GAGAAGACCATTATCATCACATGCAGCTTCACGCCAGGCTCCTGTACACT"
            "GACGGCCTACAAGCTGACCCCCAGTGGCTACGAATGGGGCCGCCAGAACA"
            "CAGACAAGGGCAACAACCCCAAGGGCTACCTGCCTTCACACTATGAGAGG"
            "GTGCAGATGCTGCTGTCGGACCGTTTCCTTGGCTTCTTCATGGTCCCTGC"
            "CCAGTCCTCGTGGAACTACAACTTCATGGGTGTTCGGCATGACCCCAACA"
            "TGAAATATGAGCTACAGCTGGCGAACCCCAAAGAGTTCTACCACGAGGTG"
            "CACAGGCCCTCTCACTTCCTCAACTTTGCTCTCCTGCAGGAGGGGGAGGT"
            "TTACTCTGCGGATCGGGAGGACCTGTATGCCTGACCGTTTCCCTGCCTCC"
            "TGCTTCAGCCTCCCGAGGCCGAAGCCTCAGCCCCTCCAGACAGGCCGCTG"
            "ACATTCAGCAGTTTGGCCTCTTTCCCTCTGTCTGTGCTTGTGTTGTTGAC"
            "CTCCTGATGGCTTGTCATCCTGAATAAAATATAATAATAAATTTTGTATA"
            "AATAGGA",
            "query_name": "four",
            "lt_soft_len": 0,
            "rt_soft_len": 670,
            "read_match_size": 937,
            "reference_match_size": 2957,
            "indel_size": 2020,
            "cigartuples_without_soft": [
                [0, 637],
                [3, 1753],
                [0, 108],
                [3, 267],
                [0, 192],
            ],
            "cigartuples": [
                (0, 637),
                (3, 1753),
                (0, 108),
                (3, 267),
                (0, 192),
                (4, 670),
            ],
            "query_length": 1607,
            "adhocsms": None,
            "adhocseq": None,
            "mode": None,
            "sms": (0, 937, 670),
            "ref_end": 1730946,
        },
    ]

    read_instances = []
    for read_param in param_dict:
        read_instances.append(
            Read.new(**{param: read_param[param] for param in read_init_params}, query_qualities=[30] * len(read_param["query_seq"])),  # type: ignore
        )
    return read_instances


@pytest.fixture()
def trans_same_strand_reads():
    """Reads fixture."""
    read_init_params = [
        "query_name",
        "chrom",
        "ref_start",
        "strand",
        "cigar_str",
        "mapq",
        "nm",
        "query_seq",
    ]

    param_dict = [
        {
            "chrom": "chr17",
            "ref_start": 1744991,
            "strand": "+",
            "cigar_str": "67M116N39M119N76M1652S",
            "mapq": 60,
            "nm": 0,
            "query_seq": "GAACATGGCGCTGCTCTGGGGGCTCCTGGTGCTCAGCTGGTCCTGCCTGC"
            "AAGGCCCCTGCTCCGTGTTCTCCCCTGTGAGCGCCATGGAGCCCTTGGGC"
            "CGGCAGCTAACTAGCGGGCCGAACCAGGAGCAGGTGTCCCCACTTACCCT"
            "CCTCAAGTTGGGCAACCAGGTACAACCAGGTGTACCCCGTCCAGGAAGCC"
            "CTGGCCGTGCTGGAGCCCTATGCGCGGCTGCCCCCGCACAAGCATGTGGC"
            "TCGGCCCACTGAGGTCCTGGCTGGTACCCAGCTCCTCTACGCCTTTTTCA"
            "CTCGGACCCATGGGGACATGCACAGCCTGGTGCGAAGCCGCCACCGTATC"
            "CCTGAGCCTGAGGCTGCCGTGCTCTTCCGCCAGATGGCCACCGCCCTGGC"
            "GCACTGTCACCAGCACGGTCTGGTCCTGCGTGATCTCAAGCTGTGTCGCT"
            "TTGTCTTCGCTGACCGTGAGAGGAAGAAGCTGGTGCTGGAGAACCTGGAG"
            "GACTCCTGCGTGCTGACTGGGCCAGATGATTCCCTGTGGGACAAGCACGC"
            "GTGCCCAGCCTACGTGGGACCTGAGATACTCAGCTCACGGGCCTCATACT"
            "CGGGCAAGGCAGCCGATGTCTGGAGCCTGGGCGTGGCGCTCTTCACCATG"
            "CTGGCCGGCCACTACCCCTTCCAGGACTCGGAGCCTGTCCTGCTCTTCGG"
            "CAAGATCCGCCGCGGGGCCTACGCCTTGCCTGCAGGCCTCTCGGCCCCTG"
            "CCCGCTGTCTGGTTCGCTGCCTCCTTCGTCGGGAGCCAGCTGAACGGCTC"
            "ACAGCCACAGGCATCCTCCTGCACCCCTGGCTGCGACAGGACCCGATGCC"
            "CTTAGCCCCAACCCGATCCCATCTCTGGGAGGCTGCCCAGGTGGTCCCTG"
            "ATGGACTGGGGCTGGACGAAGCCAGGGAAGAGGAGGGAGACAGAGAAGTG"
            "GTTCTGTATGGCTAGGACCACCCTACTACACGCTCAGCTGCCAACAGTGG"
            "ATTGAGTTTGGGGGTAGCTCCAAGCCTTCTCCTGCCTCTGAACTGAGCCA"
            "AACCTTCAGTGCCTTCCAGAAGGGAGAAAGGCAGAAGCCTGTGTGGAGTG"
            "TGCTGTGTACACATCTGCTTTGTTCCACACACATGCAGTTCCTGCTTGGG"
            "TGCTTATCAGGTGCCAAGCCCTGTTCTCGGTGCTGGGAGTACAGCAGTGA"
            "GCAAAGGAGACAATATTCCCTGCTCACAGAGATGACAAACTGGCATCCTT"
            "GAGCTGACAACACTTTTCCATGACCATAGGTCACTGTCTACACTGGGTAC"
            "ACTTTGTACCAGTGTCGGCCTCCACTGATGCTGGTGCTCAGGCACCTCTG"
            "TCCAAGGACAATCCCTTTCACAAACAAACCAGCTGCCTTTGTATCTTGTA"
            "CCTTTTCAGAGAAAGGGAGGTATCCCTGTGCCAAAGGCTCCAGGCCTCTC"
            "CCCTGCAACTCAGGACCCAAGCCCAGCTCACTCTGGGAACTGTGTTCCCA"
            "GCATCTCTGTCCTCTTGATTAAGAGATTCTCCTTCCAGGCCTAAGCCTGG"
            "GATTTGGGCCAGAGATAAGAATCCAAACTATGAGGCTAGTTCTTGTCTAA"
            "CTCAAGACTGTTCTGGAATGAGGGTCCAGGCCTGTCAACCATGGGGCTTC"
            "TGACCTGAGCACCAAGGTTGAGGGACAGGATTAGGCAGGGTCTGTCCTGT"
            "GGCCACCTGGAAAGTCCCAGGTGGGACTCTTCTGGGGACACTTGGGGTCC"
            "ACAATCCCAGGTCCATACTCTAGGTTTTGGATACCATGAGTATGTATGTT"
            "TACCTGTGCCTAATAAAGGAGAATTATGAAATAA",
            "query_name": "two",
            "lt_soft_len": 0,
            "rt_soft_len": 1652,
            "read_match_size": 182,
            "reference_match_size": 417,
            "indel_size": 235,
            "cigartuples_without_soft": [[0, 67], [3, 116], [0, 39], [3, 119], [0, 76]],
            "cigartuples": [(0, 67), (3, 116), (0, 39), (3, 119), (0, 76), (4, 1652)],
            "query_length": 1834,
            "adhocsms": None,
            "adhocseq": None,
            "mode": None,
            "sms": (0, 182, 1652),
            "ref_end": 1745408,
        },
        {
            "chrom": "chr20",
            "ref_start": 391283,
            "strand": "+",
            "cigar_str": "176S296M4618N1362M",
            "mapq": 60,
            "nm": 0,
            "query_seq": "GAACATGGCGCTGCTCTGGGGGCTCCTGGTGCTCAGCTGGTCCTGCCTGC"
            "AAGGCCCCTGCTCCGTGTTCTCCCCTGTGAGCGCCATGGAGCCCTTGGGC"
            "CGGCAGCTAACTAGCGGGCCGAACCAGGAGCAGGTGTCCCCACTTACCCT"
            "CCTCAAGTTGGGCAACCAGGTACAACCAGGTGTACCCCGTCCAGGAAGCC"
            "CTGGCCGTGCTGGAGCCCTATGCGCGGCTGCCCCCGCACAAGCATGTGGC"
            "TCGGCCCACTGAGGTCCTGGCTGGTACCCAGCTCCTCTACGCCTTTTTCA"
            "CTCGGACCCATGGGGACATGCACAGCCTGGTGCGAAGCCGCCACCGTATC"
            "CCTGAGCCTGAGGCTGCCGTGCTCTTCCGCCAGATGGCCACCGCCCTGGC"
            "GCACTGTCACCAGCACGGTCTGGTCCTGCGTGATCTCAAGCTGTGTCGCT"
            "TTGTCTTCGCTGACCGTGAGAGGAAGAAGCTGGTGCTGGAGAACCTGGAG"
            "GACTCCTGCGTGCTGACTGGGCCAGATGATTCCCTGTGGGACAAGCACGC"
            "GTGCCCAGCCTACGTGGGACCTGAGATACTCAGCTCACGGGCCTCATACT"
            "CGGGCAAGGCAGCCGATGTCTGGAGCCTGGGCGTGGCGCTCTTCACCATG"
            "CTGGCCGGCCACTACCCCTTCCAGGACTCGGAGCCTGTCCTGCTCTTCGG"
            "CAAGATCCGCCGCGGGGCCTACGCCTTGCCTGCAGGCCTCTCGGCCCCTG"
            "CCCGCTGTCTGGTTCGCTGCCTCCTTCGTCGGGAGCCAGCTGAACGGCTC"
            "ACAGCCACAGGCATCCTCCTGCACCCCTGGCTGCGACAGGACCCGATGCC"
            "CTTAGCCCCAACCCGATCCCATCTCTGGGAGGCTGCCCAGGTGGTCCCTG"
            "ATGGACTGGGGCTGGACGAAGCCAGGGAAGAGGAGGGAGACAGAGAAGTG"
            "GTTCTGTATGGCTAGGACCACCCTACTACACGCTCAGCTGCCAACAGTGG"
            "ATTGAGTTTGGGGGTAGCTCCAAGCCTTCTCCTGCCTCTGAACTGAGCCA"
            "AACCTTCAGTGCCTTCCAGAAGGGAGAAAGGCAGAAGCCTGTGTGGAGTG"
            "TGCTGTGTACACATCTGCTTTGTTCCACACACATGCAGTTCCTGCTTGGG"
            "TGCTTATCAGGTGCCAAGCCCTGTTCTCGGTGCTGGGAGTACAGCAGTGA"
            "GCAAAGGAGACAATATTCCCTGCTCACAGAGATGACAAACTGGCATCCTT"
            "GAGCTGACAACACTTTTCCATGACCATAGGTCACTGTCTACACTGGGTAC"
            "ACTTTGTACCAGTGTCGGCCTCCACTGATGCTGGTGCTCAGGCACCTCTG"
            "TCCAAGGACAATCCCTTTCACAAACAAACCAGCTGCCTTTGTATCTTGTA"
            "CCTTTTCAGAGAAAGGGAGGTATCCCTGTGCCAAAGGCTCCAGGCCTCTC"
            "CCCTGCAACTCAGGACCCAAGCCCAGCTCACTCTGGGAACTGTGTTCCCA"
            "GCATCTCTGTCCTCTTGATTAAGAGATTCTCCTTCCAGGCCTAAGCCTGG"
            "GATTTGGGCCAGAGATAAGAATCCAAACTATGAGGCTAGTTCTTGTCTAA"
            "CTCAAGACTGTTCTGGAATGAGGGTCCAGGCCTGTCAACCATGGGGCTTC"
            "TGACCTGAGCACCAAGGTTGAGGGACAGGATTAGGCAGGGTCTGTCCTGT"
            "GGCCACCTGGAAAGTCCCAGGTGGGACTCTTCTGGGGACACTTGGGGTCC"
            "ACAATCCCAGGTCCATACTCTAGGTTTTGGATACCATGAGTATGTATGTT"
            "TACCTGTGCCTAATAAAGGAGAATTATGAAATAA",
            "query_name": "two",
            "lt_soft_len": 176,
            "rt_soft_len": 0,
            "read_match_size": 1658,
            "reference_match_size": 6276,
            "indel_size": 4618,
            "cigartuples_without_soft": [[0, 296], [3, 4618], [0, 1362]],
            "cigartuples": [(4, 176), (0, 296), (3, 4618), (0, 1362)],
            "query_length": 1834,
            "adhocsms": None,
            "adhocseq": None,
            "mode": None,
            "sms": (176, 1658, 0),
            "ref_end": 397559,
        },
    ]

    read_instances = []
    for read_param in param_dict:
        read_instances.append(
            Read.new(**{param: read_param[param] for param in read_init_params}, query_qualities=[30] * len(read_param["query_seq"])),  # type: ignore
        )
    return read_instances


@pytest.fixture()
def trans_diff_strand_reads():
    """Reads fixture."""
    read_init_params = [
        "query_name",
        "chrom",
        "ref_start",
        "strand",
        "cigar_str",
        "mapq",
        "nm",
        "query_seq",
    ]

    param_dict = [
        {
            "chrom": "chr17",
            "ref_start": 1744991,
            "strand": "+",
            "cigar_str": "67M116N39M119N73M3550S",
            "mapq": 60,
            "nm": 0,
            "query_seq": "GAACATGGCGCTGCTCTGGGGGCTCCTGGTGCTCAGCTGGTCCTGCCTGC"
            "AAGGCCCCTGCTCCGTGTTCTCCCCTGTGAGCGCCATGGAGCCCTTGGGC"
            "CGGCAGCTAACTAGCGGGCCGAACCAGGAGCAGGTGTCCCCACTTACCCT"
            "CCTCAAGTTGGGCAACCAGGTACAACCAGATTGTGTTGTATCGCGAGCAG"
            "GAAGTCCTGGACTGTGACTGTGACATGGCCTCGGTCCACCACCTGTTGTC"
            "CCAGATCCCTCAGGACTTGCCCTATGAGACACTGATCAGCAGAGCAGGAG"
            "ACCTTTTTGTTCAGTTTCCCCCATCCGAACTTGCTCGGGAGGCCGCTGCC"
            "CAACAGCAAGCTGAGAGGACGGCAGCCTCTACTTTCAAAGACTTTGAGCT"
            "GGCATCAGCCCAGCAGAGGCCTGATATGGTGCTGCGGCAGCGGTTTCGGG"
            "GACTTCTGCGGCCTGAAGATCGAACAAAAGATGTCCTGACCAAGCCAAGG"
            "ACCAACCGCTTTGTGAAATTGGCAGTGATGGGGCTGACAGTGGCACTTGG"
            "AGCGGCTGCACTGGCTGTGGTGAAAAGTGCCCTGGAATGGGCCCCTAAGT"
            "TTCAGCTGCAGCTGTTTCCCTGAAAGCCAGAGAAGACCTTCCTCTTACAT"
            "CACATTAAGGTCTCACCCTTCCATGGAAGGATTGGGAGGGGTGGAATTTC"
            "CTTTATTAAAAGGGTTTCTGTCCAGAGTTTTTTATTCCTGCCACCCTGCC"
            "CTGCCCGTTTGTGTTTGCCTTTACTTCAGAGGCCAGTAGCAGAGCCTACC"
            "TGACACAGAGGGGACCTGGGGGCCTGGCACAGAATCTTATGCCTCTCCCA"
            "GTGGGCTTTTGGATGGGCTCTCTGCCACCTCCCTGGTGTTGGAGGAAGTG"
            "GGTTTCTGAAGCTTGCAGCTGCTTTTGCAACCTGCTGGGCCTGGGCTGCC"
            "CTAGTTACCGGGAACCTCCTAGTCACCCCATAGAAGGTGAACTGGAACAT"
            "GGGATGCCCTCTTACTGCTCCTGCTTGCCTGCATCAGATGGACACAGAAG"
            "GAGGGGGCTGCTGCTGAAGGAGTCAGGCTTGGGATGGAGAGCAAGAGGCC"
            "AAAGGACTCGTCTGGGAGCATGATCGGCCCCTCTTACTAGCAGCTCCATC"
            "AGCTGATCAGAAATCAGAGACAGAAGGGAACTAGGTTACTCGTTAAATCC"
            "TACCTATTTTCAGCCTAGAAATCACATGGGCGTTTCCAGTCAAGTGGGAA"
            "GGAAGCTCATTTTTAGGGCCTAGACCTAGACTAGTTTTGCCTGCCTTTTT"
            "TTCCTCCCTGCTTTCTTCTACAAGCCACACAACATTGCTTATAAAAGGTA"
            "CTTTTATTACTATTTTTAGAATATATACACCCCATATGTAAATTACCCTC"
            "ACTTTTAAAGTAATAATAGTTCCTTCACGGAAAAAAAAATAGTTCTCATC"
            "AGAAGGATGAGCTTCTAAGATCCTGAATTTTACTTTCTACTTGATTAACA"
            "TTTTCGCTTTAGCCAGAGTTGCTATTTGCAAACAGCTTTCCACTTCCAAA"
            "GTGCCACTTTCTGACCGGTTTTTCTTCCTGTTTTCCTCAAATCATCCTAC"
            "TCCCAAATAGGCACCCACTCACTACCTTGGCGTCGTTTTTTGGGTCTGAC"
            "TTGACTCGTCAACTGCTGGTCTCTCCCACCTGGTTGGAAATGTCGTTGGA"
            "AACTTGCAAAGACTCTCCAGACCTTAGGGAACAAGAGGCATCACTCAGTC"
            "CTTCTGGGACAGCTTCCCTGTAAGCAAAGCCAGGTTTGTTTTAGATTCAC"
            "TCTGGCCTGAAAAAAAAAGTGCCTTTTGCTGCTTTAAAGAATTGGGGTAT"
            "ATGGTATGAAGCAGCCATGTACTTGTATTTTCCTGGTCTTTCCTGGGCAC"
            "TCTTCTCTCTTGGCAGATGTTTTCTTAAAGTGAACACACCAGAAGCACTC"
            "TACCCCACCATATCCAGTCCTCTTTGCATGCCTGTTGTGTGCAGGGTGGA"
            "GGGTGTCCCACGTGCCAGAGCAGCTGGGAGCCCTGTCCGCTGAGTTACAC"
            "TAAGCACTTTATTTTTATTTATTTTATTATTATTTTCTTTTTTCTGAGAT"
            "GGAGTCTCACTCTGTTGCCCAGGCTGGAGTGCAGTGGTGCAGTCTCAGCT"
            "CACTGCAACCTCCGCCTCCCAAGTTCAGGCAATTCTCGCTGCCTCAGCCT"
            "CCCGAGTAGCTGGGACTACAGGCACCTGCTACCACGCCTGACTAATTTTT"
            "GTATTTTTAGTAGAGATGGGGTTTCGCCACGTTGGCCAGGCTGGTCTCGA"
            "ACTCCTGACCTCAGGTGATCTGCCCGTCTCGTCCTCCCAAAGTGCTGGGA"
            "TTACAGGTGTGAGCCACCACGCCCAGCCACCACTACGCACTTTAAAACCA"
            "AAAAAAGCTCAAAGGGATGGATCATTGTCCATGGCTCAGGAGCCCCACTG"
            "TGGGGTAAGTGTGATGTCGATGGATTAATTTAGACAGTGGTGTATTCATC"
            "AGGGCAAAGGAAATTCTTCCAGAGGTGATGATGCGGCAGATATTCCCAGT"
            "GCTCTCCCAAAGCAAGCTGGCCCTCTTGTCATCCTCTCAGTGGGCGGCAC"
            "CAGCTGCCCCTCCTTCCACAAGTACTCAAGCCTGTTTGTAAATACTGAAG"
            "GAATTGATGGGGTTGAGGAAAGGAGGTGCATGTGACCAGGGTCCCAAGGC"
            "CACAGCTTTTCAGATCCTAGGAAGCAAGTGGCATTTGCTTGAGTTGTGGC"
            "CTCGGAAGGAGAATGTTTATCTGTTTTCTAACTTTGCTGACACCAGGATT"
            "CTCCCTGTCATTGAGAAGAAAGCATTATCTAATTACCTTCAGGTGGTTTA"
            "CTTATTCTGTAAAGAATATGTGTAAATATTTTGTACAGAGCCCTGTATCA"
            "AATAAACAGCCATATGTGGTTACTAATCACCTCTTCTGTCATTCCGTCCT"
            "TGGCCACCGCTCAGTGGGAATGGTCTCTGATCTGGATGCTCCCACCTTCC"
            "ATGTCAGGCCCAGAACTGTGCCATGGTCTGTGGACTCCTGGTCAGCCTTG"
            "ACTGGCTAGGAGACCTTGGGCAGTACCTACAGTCTTGCTGTTTCTGTTTC"
            "ATCTGCAAGAATTATGACCCACACACTCCAGCTGCAGCCCAGGGCACTGT"
            "GATATTTTATACGTGTGTAGATGTTTTTGTCCACAGTTCCTGGTTCATCA"
            "CTCCCATAACCCTTTGTTATAATGTTGGGACACTGCAGGCCTCAGAAAAC"
            "GGAATCTCTGTCTGTGACCTTCTCCTGCCCCATTTCACTTGCTCAACACC"
            "AGACTTTAATCTGACTGTAGCTCATAAGACCCTCATTCCAGAGAGGGTGC"
            "TGCCCCATACCCGGAAGGAGGAACGCTGCACAGAGAGGCCAAGAAGCATC"
            "TGGACAGACAGGCCTTGCTGGGTTTAGACCTTATGCTTTTTGTCCAGTTT"
            "CATCTCAACACAGCTGCCATGCTTCAGCCATGCCTATCCAATGACGTCTC"
            "CATAAAAGGCCCAGGAACACGGGAGCTTCTGAAGAGCTGAACATGTGGAG"
            "GGAGGGGAACGAGAACTTGTCCATGTGCCAAGAGGGTGGCGCACCCCCAC"
            "TCCATGGGGACAGAAGCTCCAGCATTTGCCCAGGACCCGTCCAGACCTCA"
            "CCCTGTGTGTATCTTCATCTGGCTGTTTACTTATTTGTATCCTTTTCTAA"
            "TAATGTTTGTAATAAACTGGTAAACATAA",
            "query_name": "three",
            "lt_soft_len": 0,
            "rt_soft_len": 3550,
            "read_match_size": 179,
            "reference_match_size": 414,
            "indel_size": 235,
            "cigartuples_without_soft": [[0, 67], [3, 116], [0, 39], [3, 119], [0, 73]],
            "cigartuples": [(0, 67), (3, 116), (0, 39), (3, 119), (0, 73), (4, 3550)],
            "query_length": 3729,
            "adhocsms": None,
            "adhocseq": None,
            "mode": None,
            "sms": (0, 179, 3550),
            "ref_end": 1745405,
        },
        {
            "chrom": "chr20",
            "ref_start": 435479,
            "strand": "-",
            "cigar_str": "3362M266N191M176S",
            "mapq": 60,
            "nm": 0,
            "query_seq": "TTATGTTTACCAGTTTATTACAAACATTATTAGAAAAGGATACAAATAAG"
            "TAAACAGCCAGATGAAGATACACACAGGGTGAGGTCTGGACGGGTCCTGG"
            "GCAAATGCTGGAGCTTCTGTCCCCATGGAGTGGGGGTGCGCCACCCTCTT"
            "GGCACATGGACAAGTTCTCGTTCCCCTCCCTCCACATGTTCAGCTCTTCA"
            "GAAGCTCCCGTGTTCCTGGGCCTTTTATGGAGACGTCATTGGATAGGCAT"
            "GGCTGAAGCATGGCAGCTGTGTTGAGATGAAACTGGACAAAAAGCATAAG"
            "GTCTAAACCCAGCAAGGCCTGTCTGTCCAGATGCTTCTTGGCCTCTCTGT"
            "GCAGCGTTCCTCCTTCCGGGTATGGGGCAGCACCCTCTCTGGAATGAGGG"
            "TCTTATGAGCTACAGTCAGATTAAAGTCTGGTGTTGAGCAAGTGAAATGG"
            "GGCAGGAGAAGGTCACAGACAGAGATTCCGTTTTCTGAGGCCTGCAGTGT"
            "CCCAACATTATAACAAAGGGTTATGGGAGTGATGAACCAGGAACTGTGGA"
            "CAAAAACATCTACACACGTATAAAATATCACAGTGCCCTGGGCTGCAGCT"
            "GGAGTGTGTGGGTCATAATTCTTGCAGATGAAACAGAAACAGCAAGACTG"
            "TAGGTACTGCCCAAGGTCTCCTAGCCAGTCAAGGCTGACCAGGAGTCCAC"
            "AGACCATGGCACAGTTCTGGGCCTGACATGGAAGGTGGGAGCATCCAGAT"
            "CAGAGACCATTCCCACTGAGCGGTGGCCAAGGACGGAATGACAGAAGAGG"
            "TGATTAGTAACCACATATGGCTGTTTATTTGATACAGGGCTCTGTACAAA"
            "ATATTTACACATATTCTTTACAGAATAAGTAAACCACCTGAAGGTAATTA"
            "GATAATGCTTTCTTCTCAATGACAGGGAGAATCCTGGTGTCAGCAAAGTT"
            "AGAAAACAGATAAACATTCTCCTTCCGAGGCCACAACTCAAGCAAATGCC"
            "ACTTGCTTCCTAGGATCTGAAAAGCTGTGGCCTTGGGACCCTGGTCACAT"
            "GCACCTCCTTTCCTCAACCCCATCAATTCCTTCAGTATTTACAAACAGGC"
            "TTGAGTACTTGTGGAAGGAGGGGCAGCTGGTGCCGCCCACTGAGAGGATG"
            "ACAAGAGGGCCAGCTTGCTTTGGGAGAGCACTGGGAATATCTGCCGCATC"
            "ATCACCTCTGGAAGAATTTCCTTTGCCCTGATGAATACACCACTGTCTAA"
            "ATTAATCCATCGACATCACACTTACCCCACAGTGGGGCTCCTGAGCCATG"
            "GACAATGATCCATCCCTTTGAGCTTTTTTTGGTTTTAAAGTGCGTAGTGG"
            "TGGCTGGGCGTGGTGGCTCACACCTGTAATCCCAGCACTTTGGGAGGACG"
            "AGACGGGCAGATCACCTGAGGTCAGGAGTTCGAGACCAGCCTGGCCAACG"
            "TGGCGAAACCCCATCTCTACTAAAAATACAAAAATTAGTCAGGCGTGGTA"
            "GCAGGTGCCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCAGCGAGAATTG"
            "CCTGAACTTGGGAGGCGGAGGTTGCAGTGAGCTGAGACTGCACCACTGCA"
            "CTCCAGCCTGGGCAACAGAGTGAGACTCCATCTCAGAAAAAAGAAAATAA"
            "TAATAAAATAAATAAAAATAAAGTGCTTAGTGTAACTCAGCGGACAGGGC"
            "TCCCAGCTGCTCTGGCACGTGGGACACCCTCCACCCTGCACACAACAGGC"
            "ATGCAAAGAGGACTGGATATGGTGGGGTAGAGTGCTTCTGGTGTGTTCAC"
            "TTTAAGAAAACATCTGCCAAGAGAGAAGAGTGCCCAGGAAAGACCAGGAA"
            "AATACAAGTACATGGCTGCTTCATACCATATACCCCAATTCTTTAAAGCA"
            "GCAAAAGGCACTTTTTTTTTCAGGCCAGAGTGAATCTAAAACAAACCTGG"
            "CTTTGCTTACAGGGAAGCTGTCCCAGAAGGACTGAGTGATGCCTCTTGTT"
            "CCCTAAGGTCTGGAGAGTCTTTGCAAGTTTCCAACGACATTTCCAACCAG"
            "GTGGGAGAGACCAGCAGTTGACGAGTCAAGTCAGACCCAAAAAACGACGC"
            "CAAGGTAGTGAGTGGGTGCCTATTTGGGAGTAGGATGATTTGAGGAAAAC"
            "AGGAAGAAAAACCGGTCAGAAAGTGGCACTTTGGAAGTGGAAAGCTGTTT"
            "GCAAATAGCAACTCTGGCTAAAGCGAAAATGTTAATCAAGTAGAAAGTAA"
            "AATTCAGGATCTTAGAAGCTCATCCTTCTGATGAGAACTATTTTTTTTTC"
            "CGTGAAGGAACTATTATTACTTTAAAAGTGAGGGTAATTTACATATGGGG"
            "TGTATATATTCTAAAAATAGTAATAAAAGTACCTTTTATAAGCAATGTTG"
            "TGTGGCTTGTAGAAGAAAGCAGGGAGGAAAAAAAGGCAGGCAAAACTAGT"
            "CTAGGTCTAGGCCCTAAAAATGAGCTTCCTTCCCACTTGACTGGAAACGC"
            "CCATGTGATTTCTAGGCTGAAAATAGGTAGGATTTAACGAGTAACCTAGT"
            "TCCCTTCTGTCTCTGATTTCTGATCAGCTGATGGAGCTGCTAGTAAGAGG"
            "GGCCGATCATGCTCCCAGACGAGTCCTTTGGCCTCTTGCTCTCCATCCCA"
            "AGCCTGACTCCTTCAGCAGCAGCCCCCTCCTTCTGTGTCCATCTGATGCA"
            "GGCAAGCAGGAGCAGTAAGAGGGCATCCCATGTTCCAGTTCACCTTCTAT"
            "GGGGTGACTAGGAGGTTCCCGGTAACTAGGGCAGCCCAGGCCCAGCAGGT"
            "TGCAAAAGCAGCTGCAAGCTTCAGAAACCCACTTCCTCCAACACCAGGGA"
            "GGTGGCAGAGAGCCCATCCAAAAGCCCACTGGGAGAGGCATAAGATTCTG"
            "TGCCAGGCCCCCAGGTCCCCTCTGTGTCAGGTAGGCTCTGCTACTGGCCT"
            "CTGAAGTAAAGGCAAACACAAACGGGCAGGGCAGGGTGGCAGGAATAAAA"
            "AACTCTGGACAGAAACCCTTTTAATAAAGGAAATTCCACCCCTCCCAATC"
            "CTTCCATGGAAGGGTGAGACCTTAATGTGATGTAAGAGGAAGGTCTTCTC"
            "TGGCTTTCAGGGAAACAGCTGCAGCTGAAACTTAGGGGCCCATTCCAGGG"
            "CACTTTTCACCACAGCCAGTGCAGCCGCTCCAAGTGCCACTGTCAGCCCC"
            "ATCACTGCCAATTTCACAAAGCGGTTGGTCCTTGGCTTGGTCAGGACATC"
            "TTTTGTTCGATCTTCAGGCCGCAGAAGTCCCCGAAACCGCTGCCGCAGCA"
            "CCATATCAGGCCTCTGCTGGGCTGATGCCAGCTCAAAGTCTTTGAAAGTA"
            "GAGGCTGCCGTCCTCTCAGCTTGCTGTTGGGCAGCGGCCTCCCGAGCAAG"
            "TTCGGATGGGGGAAACTGAACAAAAAGGTCTCCTGCTCTGCTGATCAGTG"
            "TCTCATAGGGCAAGTCCTGAGGGATCTGGGACAACAGGTGGTGGACCGAG"
            "GCCATGTCACAGTCACAGTCCAGGACTTCCTGCTCGCGATACAACACAAT"
            "CTGGTTGTACCTGGTTGCCCAACTTGAGGAGGGTAAGTGGGGACACCTGC"
            "TCCTGGTTCGGCCCGCTAGTTAGCTGCCGGCCCAAGGGCTCCATGGCGCT"
            "CACAGGGGAGAACACGGAGCAGGGGCCTTGCAGGCAGGACCAGCTGAGCA"
            "CCAGGAGCCCCCAGAGCAGCGCCATGTTC",
            "query_name": "three",
            "lt_soft_len": 0,
            "rt_soft_len": 176,
            "read_match_size": 3553,
            "reference_match_size": 3819,
            "indel_size": 266,
            "cigartuples_without_soft": [[0, 3362], [3, 266], [0, 191]],
            "cigartuples": [(0, 3362), (3, 266), (0, 191), (4, 176)],
            "query_length": 3729,
            "adhocsms": None,
            "adhocseq": None,
            "mode": None,
            "sms": (0, 3553, 176),
            "ref_end": 439298,
        },
    ]

    read_instances = []
    for read_param in param_dict:
        read_instances.append(
            Read.new(**{param: read_param[param] for param in read_init_params}, query_qualities=[30] * len(read_param["query_seq"])),  # type: ignore
        )
    return read_instances


@pytest.fixture()
def tdup_reads():
    """Reads fixture."""
    read_init_params = [
        "query_name",
        "chrom",
        "ref_start",
        "strand",
        "cigar_str",
        "mapq",
        "nm",
        "query_seq",
    ]

    param_dict = [
        {
            "chrom": "chr17",
            "ref_start": 1364856,
            "strand": "-",
            "cigar_str": "299S202M34988N176M",
            "mapq": 60,
            "nm": 0,
            "query_seq": "TAAGACTAGGAATGGAGCAGTTCAGTCTAAAAAATATCACAGGTAACAGA"
            "ATGCTTATATAAACTAGACTGCTTTTGACATCTGTAAGAAAATTGTATAG"
            "ATGGCAGTTGGAAAAAAAAAAAAAAGATTGTTCCCATCTGTCAGCAAAAC"
            "TGTTGAACTATACTCAGCTGAAGTCCTCATCGGGATTCTGTTGATCCAGC"
            "AGACGGACATGTGTGAATGGGAAGTGACCTCGTTTGCCATTACACTCCCC"
            "TTCCCACTGACCACTCACATTAATCTTCGTAACCTTTACCAGCTCACCGA"
            "CCATTTGCCGATATTCCCGAATCATTTTTAGCTTGTCTTCTCCTCCCTTG"
            "TTTTCTTCTTTCTGTTCAATGCTGCTGATTATTCTCCAGGAGGCTCTTCT"
            "AGCTCCAATCACATTCTTATATGCAACAGATAGGAGGTTTCTTTCTTCAA"
            "CTGTCAGCTCCACATCCATCCCTGCTACTTTCTTCATTGACTCCACCATT"
            "TCGTCGTATCGCTCAGCCTGCTCGGCCAGCTTCGCCTGGTACACCAGATC"
            "CTCTCGATCATCCATAGCGGCAGCGGCTCCGGCAGGGTCTGCGCGACGGA"
            "TGGAAGCGGATAGTGTCTCCGACTCTCTCAGCCTCTCGCTCCGCGTCCGG"
            "GCAGCAAAAATGGCGGCGCCTCAATCC",
            "query_name": "one",
            "lt_soft_len": 299,
            "rt_soft_len": 0,
            "read_match_size": 378,
            "reference_match_size": 35366,
            "indel_size": 34988,
            "cigartuples_without_soft": [[0, 202], [3, 34988], [0, 176]],
            "cigartuples": [(4, 299), (0, 202), (3, 34988), (0, 176)],
            "query_length": 677,
            "adhocsms": None,
            "adhocseq": None,
            "mode": None,
            "sms": (299, 378, 0),
            "ref_end": 1400222,
        },
        {
            "chrom": "chr17",
            "ref_start": 1423349,
            "strand": "-",
            "cigar_str": "302M375S",
            "mapq": 60,
            "nm": 0,
            "query_seq": "TAAGACTAGGAATGGAGCAGTTCAGTCTAAAAAATATCACAGGTAACAGA"
            "ATGCTTATATAAACTAGACTGCTTTTGACATCTGTAAGAAAATTGTATAG"
            "ATGGCAGTTGGAAAAAAAAAAAAAAGATTGTTCCCATCTGTCAGCAAAAC"
            "TGTTGAACTATACTCAGCTGAAGTCCTCATCGGGATTCTGTTGATCCAGC"
            "AGACGGACATGTGTGAATGGGAAGTGACCTCGTTTGCCATTACACTCCCC"
            "TTCCCACTGACCACTCACATTAATCTTCGTAACCTTTACCAGCTCACCGA"
            "CCATTTGCCGATATTCCCGAATCATTTTTAGCTTGTCTTCTCCTCCCTTG"
            "TTTTCTTCTTTCTGTTCAATGCTGCTGATTATTCTCCAGGAGGCTCTTCT"
            "AGCTCCAATCACATTCTTATATGCAACAGATAGGAGGTTTCTTTCTTCAA"
            "CTGTCAGCTCCACATCCATCCCTGCTACTTTCTTCATTGACTCCACCATT"
            "TCGTCGTATCGCTCAGCCTGCTCGGCCAGCTTCGCCTGGTACACCAGATC"
            "CTCTCGATCATCCATAGCGGCAGCGGCTCCGGCAGGGTCTGCGCGACGGA"
            "TGGAAGCGGATAGTGTCTCCGACTCTCTCAGCCTCTCGCTCCGCGTCCGG"
            "GCAGCAAAAATGGCGGCGCCTCAATCC",
            "query_name": "one",
            "lt_soft_len": 0,
            "rt_soft_len": 375,
            "read_match_size": 302,
            "reference_match_size": 302,
            "indel_size": 0,
            "cigartuples_without_soft": [[0, 302]],
            "cigartuples": [(0, 302), (4, 375)],
            "query_length": 677,
            "adhocsms": None,
            "adhocseq": None,
            "mode": None,
            "sms": (0, 302, 375),
            "ref_end": 1423651,
        },
    ]

    read_instances = []
    for read_param in param_dict:
        read_instances.append(
            Read.new(**{param: read_param[param] for param in read_init_params}, query_qualities=[30] * len(read_param["query_seq"])),  # type: ignore
        )
    return read_instances
