import re


def cigar_validity(cigar_str: str) -> str:
    """Merge the first two OR last two 'same' operations in the CIGAR string generated by BLAT.

    :param cigar_str: BLAT generated cigarstring from 'softclipped_seq2SA_tag'
    :return: valid cigarstring

    :Example:

    >>> cigarstring =  '1S2S5M3S2S'
    >>> cigar_validity(cigarstring)
    '3S5M5S'
    """
    pattern = re.compile(r"((?P<length>\d+)(?P<op>\D))")
    items_list = pattern.findall(cigar_str)
    stack = [items_list[0]]
    for item in items_list[1:]:  # [('1S', '1', 'S'),..]
        last_item = stack[-1]
        if last_item[2] == item[2]:
            length = int(last_item[1]) + int(item[1])
            stack[-1] = (f"{length}{last_item[2]}", f"{length}", last_item[2])
        else:
            stack.append(item)

    return "".join(i[0] for i in stack)
