#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import subprocess

from .exception import ToolNotFoundError

try:
    import pysam
    import numpy as np
    import HTSeq
except ModuleNotFoundError as e:
    raise SystemExit(e.msg)


def cigar_validity(cigar_str) -> str:
    """merge the first two OR last two 'same' operations in the CIGAR string generated by BLAT
    :param cigar_str: BLAT generated cigarstring from 'softclipped_seq2SA_tag'
    :type cigar_str: str
    :return: valid cigarstring
    :rtype: str
    ..note ::
        assert cigar_validity('45S50S100M1S') == '95S100M1S'
    """
    cigartuple = list(map(list, re.findall(r"(\d+)(\w)", cigar_str)))
    # first two operations are the same
    if cigartuple[0][1] == cigartuple[1][1]:
        cigartuple[1][0] = str(int(cigartuple[0][0]) + int(cigartuple[1][0]))
        del cigartuple[0]

    # last two operations are the same
    elif cigartuple[-1][1] == cigartuple[-2][1]:
        cigartuple[-2][0] = str(int(cigartuple[-1][0]) + int(cigartuple[-2][0]))
        del cigartuple[-1]

    valid_cigar = ""
    for len_str, op_str in cigartuple:
        valid_cigar = valid_cigar + len_str + op_str
    return valid_cigar


def softclipped_seq2SA_tag(
    in_seq,
    read_length,
    read_strand,
    read_mode,
    blat,
    mapq_cutoff,
    max_allowed_nm,
    blat_ident_pct_cutoff=0.95,
) -> str:
    """
    create chimeric alignments from the alignments which has a long softclipped segment but without SA tag

    :param blat:
    :param in_seq: softclipped segment of the aligned read
    :type in_seq: str
    :param read_length: the length of the aligned read
    :type read_length: int
    :param read_strand: the strand of the aligned read (-/+)
    :type read_strand: str
    :param read_mode: mode of the aligned read (1/2)
    :type read_mode: int
    :param mapq_cutoff: MAPQ cutoff
    :type mapq_cutoff: int
    :param max_allowed_nm: mismatches cutoff used for discarding supplementary alignments
    :type max_allowed_nm: int
    :param blat_ident_pct_cutoff: BLAT HSP identity cutoff
    :type blat_ident_pct_cutoff: float
    :return: putative supplementary alignment of the alignment which is ready for put in the SA tag
    :rtype: str
    """

    chimeric_aln_str = ""
    in_seq_len = len(in_seq)

    top_hsp, __mapq = blat.fetch_mapq(in_seq)

    if (
        top_hsp.ident_pct / 100 >= blat_ident_pct_cutoff
        and top_hsp.query_span / in_seq_len >= blat_ident_pct_cutoff
    ):
        __chrm_sa, __pos_sa, __strand_sa, __cigar_sa_partial, __nm_sa = blat.psl2sam(
            top_hsp, in_seq_len
        )
        if read_strand == __strand_sa:
            # same strand: different reads mode
            # MS(1) ~ SM(2) or SM(2) ~ MS(1)
            if read_mode == 1:
                __cigar_sa = "{0}S{1}".format(
                    read_length - in_seq_len, __cigar_sa_partial
                )  # SM
            else:
                __cigar_sa = "{1}{0}S".format(
                    read_length - in_seq_len, __cigar_sa_partial
                )  # MS
        else:
            # opposite strand: same reads mode
            # MS(1) ~ MS(1) or SM(2) ~ SM(2)
            if read_mode == 1:
                __cigar_sa = "{1}{0}S".format(
                    read_length - in_seq_len, __cigar_sa_partial
                )  # MS
            else:
                __cigar_sa = "{0}S{1}".format(
                    read_length - in_seq_len, __cigar_sa_partial
                )  # SM
        valid_cigar_sa = cigar_validity(__cigar_sa)
        if __mapq < mapq_cutoff and int(__nm_sa) < max_allowed_nm:
            chimeric_aln_str = "{},{},{},{},{},{};".format(
                __chrm_sa, __pos_sa, __strand_sa, valid_cigar_sa, __mapq, __nm_sa
            )
        else:
            chimeric_aln_str = ""

    return chimeric_aln_str


def external_tool_checking(logger) -> None:
    """checking dependencies are installed"""
    software = ["samtools", "gfClient", "gfServer"]
    for tool in software:
        output = subprocess.getoutput(tool)
        if "command not found" in output:
            raise ToolNotFoundError(tool)
        else:
            logger.success("Checking for '" + tool + "': found ")
